version: '3.9'

services:
  postgres:
    image: 'postgres:16'
    container_name: dq-postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: dq
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
